### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by VQ9** [VolmitSoftware/PermissionsEx#17]
How can I migrate? have you changed MySQL formatting on this branch of Pex v1?

**Comment by VQ9** [comment]
Like in terms of Pex V1 - Pex V2

**Comment by AvianAeternum** [comment]
Wut

**Comment by VQ9** [comment]
have you changed MySQL formatting on this branch of Pex v1?

**Comment by AvianAeternum** [comment]
Negative. No changes have been made to table structure or permissions formatting.
